import {
  AlertCircle, AlertTriangle, Bell, Bookmark, Cake, Camera, Check, CircleDollarSign, CircleHelp, Clock, Cloud,
  Coffee, Compass, Crown, Download, Diamond, Eye, EyeOff, ExternalLink, Flame, Gift, Gamepad2, Gem, Globe2,
  Heart, Home, Image, Info, Key, Leaf, Link, Lock, Mail, MapPin, Medal, Megaphone, MessageCircle, Mic, Monitor,
  Moon, Music, PartyPopper, Pause, Pizza, Play, Radio, Rocket, Search, Send, Settings, Shield, ShieldAlert,
  ShoppingBag, Smartphone, Snowflake, Sparkles, Star, Sun, Tag, ThumbsUp, Ticket, Trophy, Upload, User, Users,
  Video, Wifi, Wrench, X, Zap, type LucideIcon,
} from "lucide-react";

export type BannerIconOption = { id: string; label: string; Icon: LucideIcon };

export const BANNER_ICON_OPTIONS: BannerIconOption[] = [
  { id: "alert-circle", label: "Alerta", Icon: AlertCircle },
  { id: "alert-triangle", label: "Advertencia", Icon: AlertTriangle },
  { id: "bell", label: "Notificación", Icon: Bell },
  { id: "bookmark", label: "Marcador", Icon: Bookmark },
  { id: "cake", label: "Celebración", Icon: Cake },
  { id: "camera", label: "Cámara", Icon: Camera },
  { id: "check", label: "Correcto", Icon: Check },
  { id: "circle-dollar-sign", label: "Finanzas", Icon: CircleDollarSign },
  { id: "circle-help", label: "Ayuda", Icon: CircleHelp },
  { id: "clock", label: "Programado", Icon: Clock },
  { id: "cloud", label: "Nube", Icon: Cloud },
  { id: "coffee", label: "Café", Icon: Coffee },
  { id: "compass", label: "Explorar", Icon: Compass },
  { id: "crown", label: "Corona", Icon: Crown },
  { id: "download", label: "Descarga", Icon: Download },
  { id: "diamond", label: "Diamante", Icon: Diamond },
  { id: "eye", label: "Visible", Icon: Eye },
  { id: "eye-off", label: "Oculto", Icon: EyeOff },
  { id: "external-link", label: "Enlace externo", Icon: ExternalLink },
  { id: "flame", label: "Tendencia", Icon: Flame },
  { id: "gift", label: "Regalo", Icon: Gift },
  { id: "gamepad", label: "Gaming", Icon: Gamepad2 },
  { id: "gem", label: "Premium", Icon: Gem },
  { id: "globe", label: "Global", Icon: Globe2 },
  { id: "heart", label: "Comunidad", Icon: Heart },
  { id: "home", label: "Inicio", Icon: Home },
  { id: "image", label: "Imagen", Icon: Image },
  { id: "info", label: "Información", Icon: Info },
  { id: "key", label: "Clave", Icon: Key },
  { id: "leaf", label: "Naturaleza", Icon: Leaf },
  { id: "link", label: "Enlace", Icon: Link },
  { id: "lock", label: "Privacidad", Icon: Lock },
  { id: "mail", label: "Correo", Icon: Mail },
  { id: "map-pin", label: "Ubicación", Icon: MapPin },
  { id: "medal", label: "Medalla", Icon: Medal },
  { id: "megaphone", label: "Anuncio", Icon: Megaphone },
  { id: "message-circle", label: "Mensaje", Icon: MessageCircle },
  { id: "mic", label: "Micrófono", Icon: Mic },
  { id: "monitor", label: "Escritorio", Icon: Monitor },
  { id: "moon", label: "Noche", Icon: Moon },
  { id: "music", label: "Música", Icon: Music },
  { id: "party-popper", label: "Fiesta", Icon: PartyPopper },
  { id: "pause", label: "Pausa", Icon: Pause },
  { id: "pizza", label: "Comida", Icon: Pizza },
  { id: "play", label: "Reproducir", Icon: Play },
  { id: "radio", label: "Radio", Icon: Radio },
  { id: "rocket", label: "Lanzamiento", Icon: Rocket },
  { id: "search", label: "Buscar", Icon: Search },
  { id: "send", label: "Enviar", Icon: Send },
  { id: "settings", label: "Configuración", Icon: Settings },
  { id: "shield", label: "Seguridad", Icon: Shield },
  { id: "shield-alert", label: "Seguridad urgente", Icon: ShieldAlert },
  { id: "shopping-bag", label: "Tienda", Icon: ShoppingBag },
  { id: "smartphone", label: "Móvil", Icon: Smartphone },
  { id: "snowflake", label: "Invierno", Icon: Snowflake },
  { id: "sparkles", label: "Novedad", Icon: Sparkles },
  { id: "star", label: "Destacado", Icon: Star },
  { id: "sun", label: "Día", Icon: Sun },
  { id: "tag", label: "Etiqueta", Icon: Tag },
  { id: "thumbs-up", label: "Me gusta", Icon: ThumbsUp },
  { id: "ticket", label: "Evento", Icon: Ticket },
  { id: "trophy", label: "Premio", Icon: Trophy },
  { id: "upload", label: "Subida", Icon: Upload },
  { id: "user", label: "Usuario", Icon: User },
  { id: "users", label: "Usuarios", Icon: Users },
  { id: "video", label: "Vídeo", Icon: Video },
  { id: "wifi", label: "Conexión", Icon: Wifi },
  { id: "wrench", label: "Mantenimiento", Icon: Wrench },
  { id: "x", label: "Cerrar", Icon: X },
  { id: "zap", label: "Urgente", Icon: Zap },
];

export function getBannerIcon(id: string | null | undefined): LucideIcon | null {
  if (!id) return null;
  return BANNER_ICON_OPTIONS.find((option) => option.id === id)?.Icon ?? null;
}
