import { defineConfig } from "@lovable.dev/vite-tanstack-config";

// Use the standard TanStack Start server entry generated by the Lovable config.
// A custom server entry here was masking SSR failures behind a generic 500 page.
export default defineConfig({});
