import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Radio, Users, ArrowLeft } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { ChannelAvatar, VerifiedBadge } from "@/components/Media";
import { fetchProfilesByIds } from "@/lib/queries";

export const Route = createFileRoute("/live/$id")({ component: LiveViewer });
const HLS_URL = import.meta.env.VITE_LIVE_HLS_URL || "https://live.corenetwork.example/hls";

type LiveRow={id:string;user_id:string;title:string;description:string;visibility:string;stream_key:string;status:string;playback_path:string|null;viewer_count:number;started_at:string|null};
function LiveViewer(){const {id}=Route.useParams();const {data,isLoading}=useQuery({queryKey:["live",id],queryFn:async()=>{const {data:row,error}=await supabase.from("live_streams").select("*").eq("id",id).maybeSingle();if(error)throw error;if(!row)return null;const profiles=await fetchProfilesByIds([row.user_id]);return {live:row as LiveRow,channel:profiles.get(row.user_id)??null};}});if(isLoading)return <AppShell><div className="py-20 text-center text-muted-foreground">Cargando directo…</div></AppShell>;if(!data)return <AppShell><div className="py-20 text-center"><p>No encontramos esta transmisión.</p><Link to="/"><Button className="mt-4" variant="secondary">Volver</Button></Link></div></AppShell>;const src=data.live.playback_path||`${HLS_URL}/${data.live.stream_key}.m3u8`;return <AppShell><div className="mx-auto max-w-6xl space-y-5"><Link to="/" className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="mr-2 h-4 w-4"/>Volver</Link><div className="overflow-hidden rounded-2xl border border-border bg-black"><video className="aspect-video w-full" controls autoPlay playsInline src={src}/></div><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-red-600 px-3 py-1 text-xs font-bold text-white">🔴 EN VIVO</span><span className="flex items-center gap-1 text-sm text-muted-foreground"><Users className="h-4 w-4"/>{data.live.viewer_count}</span></div><h1 className="mt-2 text-2xl font-bold">{data.live.title}</h1><div className="mt-4 flex items-center gap-3"><ChannelAvatar path={data.channel?.avatar_path} name={data.channel?.display_name??"C"}/><div><p className="flex items-center gap-1 font-medium">{data.channel?.display_name||data.channel?.username}{data.channel?.is_verified&&<VerifiedBadge/>}</p><p className="text-xs text-muted-foreground">@{data.channel?.username}</p></div></div><p className="mt-5 whitespace-pre-wrap text-sm text-muted-foreground">{data.live.description}</p></div><div className="rounded-2xl border border-border bg-card p-5"><h2 className="mb-3 flex items-center gap-2 font-semibold"><Radio className="h-4 w-4"/>Chat en vivo</h2><p className="text-sm text-muted-foreground">El chat en vivo se conectará al sistema de mensajes de CoreNetwork en la siguiente fase.</p></div></div></AppShell>}
