import { Flag, Grid2X2, TerminalSquare } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ChannelAvatar, SignedImage } from "@/components/Media";
import { VideoCard } from "@/components/VideoCard";
import { CommunityFeed } from "@/components/CommunityFeed";
import { ChannelDistinctions } from "@/components/ChannelDistinctions";
import type { ChannelLayoutProps } from "./channel-data";

function Identity({ data, size = 56 }: { data: ChannelLayoutProps["data"]; size?: number }) {
  return <div className="flex items-center gap-3"><ChannelAvatar path={data.profile.avatar_path} name={data.profile.display_name || data.profile.username} size={size} /><div className="min-w-0"><h1 className="truncate font-bold">{data.profile.display_name || data.profile.username}<ChannelDistinctions className="ml-2 inline-flex" isVerified={data.profile.is_verified} isMusic={data.profile.is_music_channel} roles={data.roles} /></h1><p className="text-xs opacity-65">@{data.profile.username} · {data.profile.subscriber_count ?? data.subscriptions.length} suscriptores</p></div></div>;
}

export function TerminalChannel({ data, onSubscribe, onReport }: ChannelLayoutProps) {
  return <div className="cn-terminal-channel"><div className="cn-terminal-window"><header className="cn-terminal-header"><TerminalSquare className="h-5 w-5" /><span>cornet://channel/{data.profile.username}</span></header><div className="cn-terminal-command">$ channel open {data.profile.username}</div><section className="cn-terminal-identity"><Identity data={data} size={58} /><div className="ml-auto flex gap-2"><Button onClick={onSubscribe} size="sm" className="cn-terminal-button">{data.isSubscribed ? "unsubscribe" : "subscribe"}</Button><Button onClick={onReport} size="sm" variant="outline" className="cn-terminal-button"><Flag className="mr-1 h-3.5 w-3.5" />report</Button></div></section><div className="cn-terminal-description">{data.profile.description || "No channel description provided."}</div><section className="cn-terminal-section"><div className="cn-terminal-section-title">$ list --videos</div>{data.videos.length ? <div className="cn-terminal-video-list">{data.videos.slice(0, 12).map((video, index) => <a key={video.id} href={`/watch?v=${video.code}`} className="cn-terminal-video-row"><span className="cn-terminal-index">[{String(index + 1).padStart(2, "0")}]</span><span className="min-w-0 flex-1 truncate">{video.title}</span><span>{video.views} views</span></a>)}</div> : <p className="cn-terminal-muted">No videos found.</p>}</section><section className="cn-terminal-section"><div className="cn-terminal-section-title">$ cat featured</div>{data.videos[0] ? <div className="cn-terminal-feature"><SignedImage path={data.videos[0].thumbnail_path} alt={data.videos[0].title} className="aspect-video w-full object-cover" /><div><h2>{data.videos[0].title}</h2><p>{data.videos[0].description || "No description."}</p></div></div> : <p className="cn-terminal-muted">Nothing featured.</p>}</section></div></div>;
}

export function BentoGridChannel({ data, onSubscribe, onReport }: ChannelLayoutProps) {
  const hero = data.videos[0];
  return <div className="cn-bento-channel"><div className="cn-bento-grid"><header className="cn-bento-card cn-bento-identity"><div className="cn-bento-banner"><SignedImage path={data.profile.banner_path} alt="" className="h-full w-full object-cover" /></div><div className="cn-bento-identity-body"><Identity data={data} size={64} /><div className="flex gap-2"><Button onClick={onSubscribe} className="rounded-full">{data.isSubscribed ? "Suscrito" : "Suscribirse"}</Button><Button onClick={onReport} variant="outline" className="rounded-full"><Flag className="mr-1.5 h-4 w-4" />Denunciar</Button></div></div></header><section className="cn-bento-card cn-bento-hero"><div className="cn-bento-card-label"><Grid2X2 className="h-4 w-4" /> Destacado</div>{hero ? <><VideoCard video={hero} /><p className="mt-3 line-clamp-2 text-sm text-muted-foreground">{hero.description || ""}</p></> : <p className="text-sm text-muted-foreground">No hay video destacado.</p>}</section><section className="cn-bento-card cn-bento-stat"><strong>{data.profile.subscriber_count ?? data.subscriptions.length}</strong><span>suscriptores</span></section><section className="cn-bento-card cn-bento-stat"><strong>{data.videos.length}</strong><span>videos</span></section><section className="cn-bento-card cn-bento-about"><h2>Sobre el canal</h2><p>{data.profile.description || "Este canal todavía no tiene descripción."}</p></section><section className="cn-bento-card cn-bento-videos"><h2>Últimos videos</h2>{data.videos.length > 1 ? <div className="grid gap-4 sm:grid-cols-2">{data.videos.slice(1, 7).map((video) => <VideoCard key={video.id} video={video} />)}</div> : <p className="text-sm text-muted-foreground">Todavía no hay más videos.</p>}</section><section className="cn-bento-card cn-bento-community"><h2>Comunidad</h2><CommunityFeed channelId={data.profile.id} /></section></div></div>;
}
