/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is generated by TanStack Router. It is kept in sync with src/routes.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountSecurityRouteImport } from './routes/account-security'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminBannersRouteImport } from './routes/admin-banners'
import { Route as AdminBlogRouteImport } from './routes/admin-blog'
import { Route as AdminCampaignsRouteImport } from './routes/admin-campaigns'
import { Route as AdminMaintenanceRouteImport } from './routes/admin-maintenance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NewRouteImport } from './routes/new'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as CUsernameRouteImport } from './routes/c.$username'
import { Route as HashtagTagRouteImport } from './routes/hashtag/$tag'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as LiveUsernameRouteImport } from './routes/live.$username'
import { Route as LiveStudioRouteImport } from './routes/live.studio'
import { Route as PlaylistPlaylistIdRouteImport } from './routes/playlist.$playlistId'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AboutRoute = AboutRouteImport.update({ id: '/about', path: '/about', getParentRoute: () => rootRouteImport } as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({ id: '/account-security', path: '/account-security', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const AdminBannersRoute = AdminBannersRouteImport.update({ id: '/admin-banners', path: '/admin-banners', getParentRoute: () => rootRouteImport } as any)
const AdminBlogRoute = AdminBlogRouteImport.update({ id: '/admin-blog', path: '/admin-blog', getParentRoute: () => rootRouteImport } as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({ id: '/admin-campaigns', path: '/admin-campaigns', getParentRoute: () => rootRouteImport } as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({ id: '/admin-maintenance', path: '/admin-maintenance', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const BlogRoute = BlogRouteImport.update({ id: '/blog', path: '/blog', getParentRoute: () => rootRouteImport } as any)
const CommunityRoute = CommunityRouteImport.update({ id: '/community', path: '/community', getParentRoute: () => rootRouteImport } as any)
const ExploreRoute = ExploreRouteImport.update({ id: '/explore', path: '/explore', getParentRoute: () => rootRouteImport } as any)
const ExperimentsRoute = ExperimentsRouteImport.update({ id: '/experiments', path: '/experiments', getParentRoute: () => rootRouteImport } as any)
const HistoryRoute = HistoryRouteImport.update({ id: '/history', path: '/history', getParentRoute: () => rootRouteImport } as any)
const LiveRoute = LiveRouteImport.update({ id: '/live', path: '/live', getParentRoute: () => rootRouteImport } as any)
const MessagesRoute = MessagesRouteImport.update({ id: '/messages', path: '/messages', getParentRoute: () => rootRouteImport } as any)
const NewRoute = NewRouteImport.update({ id: '/new', path: '/new', getParentRoute: () => rootRouteImport } as any)
const NotificationsRoute = NotificationsRouteImport.update({ id: '/notifications', path: '/notifications', getParentRoute: () => rootRouteImport } as any)
const PartnerRoute = PartnerRouteImport.update({ id: '/partner', path: '/partner', getParentRoute: () => rootRouteImport } as any)
const PlaylistsRoute = PlaylistsRouteImport.update({ id: '/playlists', path: '/playlists', getParentRoute: () => rootRouteImport } as any)
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport } as any)
const RulesRoute = RulesRouteImport.update({ id: '/rules', path: '/rules', getParentRoute: () => rootRouteImport } as any)
const SeriesRoute = SeriesRouteImport.update({ id: '/series', path: '/series', getParentRoute: () => rootRouteImport } as any)
const SettingsRoute = SettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport } as any)
const ShortsRoute = ShortsRouteImport.update({ id: '/shorts', path: '/shorts', getParentRoute: () => rootRouteImport } as any)
const TermsRoute = TermsRouteImport.update({ id: '/terms', path: '/terms', getParentRoute: () => rootRouteImport } as any)
const UploadRoute = UploadRouteImport.update({ id: '/upload', path: '/upload', getParentRoute: () => rootRouteImport } as any)
const WatchRoute = WatchRouteImport.update({ id: '/watch', path: '/watch', getParentRoute: () => rootRouteImport } as any)
const AdminReportsRoute = AdminReportsRouteImport.update({ id: '/reports', path: '/reports', getParentRoute: () => AdminRoute } as any)
const CUsernameRoute = CUsernameRouteImport.update({ id: '/c/$username', path: '/c/$username', getParentRoute: () => rootRouteImport } as any)
const HashtagTagRoute = HashtagTagRouteImport.update({ id: '/hashtag/$tag', path: '/hashtag/$tag', getParentRoute: () => rootRouteImport } as any)
const LiveIndexRoute = LiveIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => LiveRoute } as any)
const LiveIdRoute = LiveIdRouteImport.update({ id: '/$id', path: '/$id', getParentRoute: () => LiveRoute } as any)
const LiveUsernameRoute = LiveUsernameRouteImport.update({ id: '/$username', path: '/$username', getParentRoute: () => LiveRoute } as any)
const LiveStudioRoute = LiveStudioRouteImport.update({ id: '/studio', path: '/studio', getParentRoute: () => LiveRoute } as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({ id: '/playlist/$playlistId', path: '/playlist/$playlistId', getParentRoute: () => rootRouteImport } as any)
const TTokenRoute = TTokenRouteImport.update({ id: '/t/$token', path: '/t/$token', getParentRoute: () => rootRouteImport } as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({ id: '/$videoId', path: '/$videoId', getParentRoute: () => WatchRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute; '/about': typeof AboutRoute; '/account-security': typeof AccountSecurityRoute; '/admin': typeof AdminRouteWithChildren; '/admin-banners': typeof AdminBannersRoute; '/admin-blog': typeof AdminBlogRoute; '/admin-campaigns': typeof AdminCampaignsRoute; '/admin-maintenance': typeof AdminMaintenanceRoute; '/auth': typeof AuthRoute; '/blog': typeof BlogRoute; '/community': typeof CommunityRoute; '/explore': typeof ExploreRoute; '/experiments': typeof ExperimentsRoute; '/history': typeof HistoryRoute; '/live': typeof LiveRouteWithChildren; '/messages': typeof MessagesRoute; '/new': typeof NewRoute; '/notifications': typeof NotificationsRoute; '/partner': typeof PartnerRoute; '/playlists': typeof PlaylistsRoute; '/privacy': typeof PrivacyRoute; '/rules': typeof RulesRoute; '/series': typeof SeriesRoute; '/settings': typeof SettingsRoute; '/shorts': typeof ShortsRoute; '/terms': typeof TermsRoute; '/upload': typeof UploadRoute; '/watch': typeof WatchRouteWithChildren; '/admin/reports': typeof AdminReportsRoute; '/c/$username': typeof CUsernameRoute; '/hashtag/$tag': typeof HashtagTagRoute; '/live/$id': typeof LiveIdRoute; '/live/$username': typeof LiveUsernameRoute; '/live/studio': typeof LiveStudioRoute; '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute; '/t/$token': typeof TTokenRoute; '/watch/$videoId': typeof WatchVideoIdRoute; '/live/': typeof LiveIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute; '/about': typeof AboutRoute; '/account-security': typeof AccountSecurityRoute; '/admin': typeof AdminRouteWithChildren; '/admin-banners': typeof AdminBannersRoute; '/admin-blog': typeof AdminBlogRoute; '/admin-campaigns': typeof AdminCampaignsRoute; '/admin-maintenance': typeof AdminMaintenanceRoute; '/auth': typeof AuthRoute; '/blog': typeof BlogRoute; '/community': typeof CommunityRoute; '/explore': typeof ExploreRoute; '/experiments': typeof ExperimentsRoute; '/history': typeof HistoryRoute; '/live': typeof LiveIndexRoute; '/messages': typeof MessagesRoute; '/new': typeof NewRoute; '/notifications': typeof NotificationsRoute; '/partner': typeof PartnerRoute; '/playlists': typeof PlaylistsRoute; '/privacy': typeof PrivacyRoute; '/rules': typeof RulesRoute; '/series': typeof SeriesRoute; '/settings': typeof SettingsRoute; '/shorts': typeof ShortsRoute; '/terms': typeof TermsRoute; '/upload': typeof UploadRoute; '/watch': typeof WatchRouteWithChildren; '/admin/reports': typeof AdminReportsRoute; '/c/$username': typeof CUsernameRoute; '/hashtag/$tag': typeof HashtagTagRoute; '/live/$id': typeof LiveIdRoute; '/live/$username': typeof LiveUsernameRoute; '/live/studio': typeof LiveStudioRoute; '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute; '/t/$token': typeof TTokenRoute; '/watch/$videoId': typeof WatchVideoIdRoute; '/live': typeof LiveIndexRoute;
}
export interface FileRoutesById extends FileRoutesByFullPath { __root__: typeof rootRouteImport }
export interface FileRouteTypes { fileRoutesByFullPath: FileRoutesByFullPath; fullPaths: keyof FileRoutesByFullPath; fileRoutesByTo: FileRoutesByTo; to: keyof FileRoutesByTo; id: keyof FileRoutesById }

declare module '@tanstack/react-router' { interface FileRoutesByPath {
  '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  '/about': { id: '/about'; path: '/about'; fullPath: '/about'; preLoaderRoute: typeof AboutRouteImport; parentRoute: typeof rootRouteImport }
  '/account-security': { id: '/account-security'; path: '/account-security'; fullPath: '/account-security'; preLoaderRoute: typeof AccountSecurityRouteImport; parentRoute: typeof rootRouteImport }
  '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
  '/admin-banners': { id: '/admin-banners'; path: '/admin-banners'; fullPath: '/admin-banners'; preLoaderRoute: typeof AdminBannersRouteImport; parentRoute: typeof rootRouteImport }
  '/admin-blog': { id: '/admin-blog'; path: '/admin-blog'; fullPath: '/admin-blog'; preLoaderRoute: typeof AdminBlogRouteImport; parentRoute: typeof rootRouteImport }
  '/admin-campaigns': { id: '/admin-campaigns'; path: '/admin-campaigns'; fullPath: '/admin-campaigns'; preLoaderRoute: typeof AdminCampaignsRouteImport; parentRoute: typeof rootRouteImport }
  '/admin-maintenance': { id: '/admin-maintenance'; path: '/admin-maintenance'; fullPath: '/admin-maintenance'; preLoaderRoute: typeof AdminMaintenanceRouteImport; parentRoute: typeof rootRouteImport }
  '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
  '/blog': { id: '/blog'; path: '/blog'; fullPath: '/blog'; preLoaderRoute: typeof BlogRouteImport; parentRoute: typeof rootRouteImport }
  '/community': { id: '/community'; path: '/community'; fullPath: '/community'; preLoaderRoute: typeof CommunityRouteImport; parentRoute: typeof rootRouteImport }
  '/explore': { id: '/explore'; path: '/explore'; fullPath: '/explore'; preLoaderRoute: typeof ExploreRouteImport; parentRoute: typeof rootRouteImport }
  '/experiments': { id: '/experiments'; path: '/experiments'; fullPath: '/experiments'; preLoaderRoute: typeof ExperimentsRouteImport; parentRoute: typeof rootRouteImport }
  '/history': { id: '/history'; path: '/history'; fullPath: '/history'; preLoaderRoute: typeof HistoryRouteImport; parentRoute: typeof rootRouteImport }
  '/live': { id: '/live'; path: '/live'; fullPath: '/live'; preLoaderRoute: typeof LiveRouteImport; parentRoute: typeof rootRouteImport }
  '/messages': { id: '/messages'; path: '/messages'; fullPath: '/messages'; preLoaderRoute: typeof MessagesRouteImport; parentRoute: typeof rootRouteImport }
  '/new': { id: '/new'; path: '/new'; fullPath: '/new'; preLoaderRoute: typeof NewRouteImport; parentRoute: typeof rootRouteImport }
  '/notifications': { id: '/notifications'; path: '/notifications'; fullPath: '/notifications'; preLoaderRoute: typeof NotificationsRouteImport; parentRoute: typeof rootRouteImport }
  '/partner': { id: '/partner'; path: '/partner'; fullPath: '/partner'; preLoaderRoute: typeof PartnerRouteImport; parentRoute: typeof rootRouteImport }
  '/playlists': { id: '/playlists'; path: '/playlists'; fullPath: '/playlists'; preLoaderRoute: typeof PlaylistsRouteImport; parentRoute: typeof rootRouteImport }
  '/privacy': { id: '/privacy'; path: '/privacy'; fullPath: '/privacy'; preLoaderRoute: typeof PrivacyRouteImport; parentRoute: typeof rootRouteImport }
  '/rules': { id: '/rules'; path: '/rules'; fullPath: '/rules'; preLoaderRoute: typeof RulesRouteImport; parentRoute: typeof rootRouteImport }
  '/series': { id: '/series'; path: '/series'; fullPath: '/series'; preLoaderRoute: typeof SeriesRouteImport; parentRoute: typeof rootRouteImport }
  '/settings': { id: '/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof rootRouteImport }
  '/shorts': { id: '/shorts'; path: '/shorts'; fullPath: '/shorts'; preLoaderRoute: typeof ShortsRouteImport; parentRoute: typeof rootRouteImport }
  '/terms': { id: '/terms'; path: '/terms'; fullPath: '/terms'; preLoaderRoute: typeof TermsRouteImport; parentRoute: typeof rootRouteImport }
  '/upload': { id: '/upload'; path: '/upload'; fullPath: '/upload'; preLoaderRoute: typeof UploadRouteImport; parentRoute: typeof rootRouteImport }
  '/watch': { id: '/watch'; path: '/watch'; fullPath: '/watch'; preLoaderRoute: typeof WatchRouteImport; parentRoute: typeof rootRouteImport }
  '/admin/reports': { id: '/admin/reports'; path: '/reports'; fullPath: '/admin/reports'; preLoaderRoute: typeof AdminReportsRouteImport; parentRoute: typeof AdminRoute }
  '/c/$username': { id: '/c/$username'; path: '/c/$username'; fullPath: '/c/$username'; preLoaderRoute: typeof CUsernameRouteImport; parentRoute: typeof rootRouteImport }
  '/hashtag/$tag': { id: '/hashtag/$tag'; path: '/hashtag/$tag'; fullPath: '/hashtag/$tag'; preLoaderRoute: typeof HashtagTagRouteImport; parentRoute: typeof rootRouteImport }
  '/live/': { id: '/live/'; path: '/'; fullPath: '/live/'; preLoaderRoute: typeof LiveIndexRouteImport; parentRoute: typeof LiveRoute }
  '/live/$id': { id: '/live/$id'; path: '/$id'; fullPath: '/live/$id'; preLoaderRoute: typeof LiveIdRouteImport; parentRoute: typeof LiveRoute }
  '/live/$username': { id: '/live/$username'; path: '/$username'; fullPath: '/live/$username'; preLoaderRoute: typeof LiveUsernameRouteImport; parentRoute: typeof LiveRoute }
  '/live/studio': { id: '/live/studio'; path: '/studio'; fullPath: '/live/studio'; preLoaderRoute: typeof LiveStudioRouteImport; parentRoute: typeof LiveRoute }
  '/playlist/$playlistId': { id: '/playlist/$playlistId'; path: '/playlist/$playlistId'; fullPath: '/playlist/$playlistId'; preLoaderRoute: typeof PlaylistPlaylistIdRouteImport; parentRoute: typeof rootRouteImport }
  '/t/$token': { id: '/t/$token'; path: '/t/$token'; fullPath: '/t/$token'; preLoaderRoute: typeof TTokenRouteImport; parentRoute: typeof rootRouteImport }
  '/watch/$videoId': { id: '/watch/$videoId'; path: '/$videoId'; fullPath: '/watch/$videoId'; preLoaderRoute: typeof WatchVideoIdRouteImport; parentRoute: typeof WatchRoute }
}}

const AdminRouteWithChildren = AdminRoute._addFileChildren({ AdminReportsRoute } as const)
const LiveRouteWithChildren = LiveRoute._addFileChildren({ LiveIdRoute, LiveUsernameRoute, LiveStudioRoute, LiveIndexRoute } as const)
const WatchRouteWithChildren = WatchRoute._addFileChildren({ WatchVideoIdRoute } as const)

const rootRouteChildren = {
  IndexRoute, AboutRoute, AccountSecurityRoute, AdminRoute: AdminRouteWithChildren, AdminBannersRoute, AdminBlogRoute, AdminCampaignsRoute, AdminMaintenanceRoute,
  AuthRoute, BlogRoute, CommunityRoute, ExploreRoute, ExperimentsRoute, HistoryRoute, LiveRoute: LiveRouteWithChildren, MessagesRoute, NewRoute,
  NotificationsRoute, PartnerRoute, PlaylistsRoute, PrivacyRoute, RulesRoute, SeriesRoute, SettingsRoute, ShortsRoute, TermsRoute, UploadRoute,
  WatchRoute: WatchRouteWithChildren, CUsernameRoute, HashtagTagRoute, PlaylistPlaylistIdRoute, TTokenRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren). _addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
