/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is generated by TanStack Router. Kept in sync for the new playlist routes.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as CUsernameRouteImport } from './routes/c.$username'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as PlaylistPlaylistIdRouteImport } from './routes/playlist.$playlistId'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const CommunityRoute = CommunityRouteImport.update({ id: '/community', path: '/community', getParentRoute: () => rootRouteImport } as any)
const ExploreRoute = ExploreRouteImport.update({ id: '/explore', path: '/explore', getParentRoute: () => rootRouteImport } as any)
const NotificationsRoute = NotificationsRouteImport.update({ id: '/notifications', path: '/notifications', getParentRoute: () => rootRouteImport } as any)
const PartnerRoute = PartnerRouteImport.update({ id: '/partner', path: '/partner', getParentRoute: () => rootRouteImport } as any)
const RulesRoute = RulesRouteImport.update({ id: '/rules', path: '/rules', getParentRoute: () => rootRouteImport } as any)
const SettingsRoute = SettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport } as any)
const UploadRoute = UploadRouteImport.update({ id: '/upload', path: '/upload', getParentRoute: () => rootRouteImport } as any)
const WatchRoute = WatchRouteImport.update({ id: '/watch', path: '/watch', getParentRoute: () => rootRouteImport } as any)
const CUsernameRoute = CUsernameRouteImport.update({ id: '/c/$username', path: '/c/$username', getParentRoute: () => rootRouteImport } as any)
const PlaylistsRoute = PlaylistsRouteImport.update({ id: '/playlists', path: '/playlists', getParentRoute: () => rootRouteImport } as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({ id: '/playlist/$playlistId', path: '/playlist/$playlistId', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/partner': typeof PartnerRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/watch': typeof WatchRoute
  '/c/$username': typeof CUsernameRoute
  '/playlists': typeof PlaylistsRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/partner': typeof PartnerRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/watch': typeof WatchRoute
  '/c/$username': typeof CUsernameRoute
  '/playlists': typeof PlaylistsRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByFullPath
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ExploreRoute: typeof ExploreRoute
  NotificationsRoute: typeof NotificationsRoute
  PartnerRoute: typeof PartnerRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  WatchRoute: typeof WatchRoute
  CUsernameRoute: typeof CUsernameRoute
  PlaylistsRoute: typeof PlaylistsRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/community': { id: '/community'; path: '/community'; fullPath: '/community'; preLoaderRoute: typeof CommunityRouteImport; parentRoute: typeof rootRouteImport }
    '/explore': { id: '/explore'; path: '/explore'; fullPath: '/explore'; preLoaderRoute: typeof ExploreRouteImport; parentRoute: typeof rootRouteImport }
    '/notifications': { id: '/notifications'; path: '/notifications'; fullPath: '/notifications'; preLoaderRoute: typeof NotificationsRouteImport; parentRoute: typeof rootRouteImport }
    '/partner': { id: '/partner'; path: '/partner'; fullPath: '/partner'; preLoaderRoute: typeof PartnerRouteImport; parentRoute: typeof rootRouteImport }
    '/rules': { id: '/rules'; path: '/rules'; fullPath: '/rules'; preLoaderRoute: typeof RulesRouteImport; parentRoute: typeof rootRouteImport }
    '/settings': { id: '/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof rootRouteImport }
    '/upload': { id: '/upload'; path: '/upload'; fullPath: '/upload'; preLoaderRoute: typeof UploadRouteImport; parentRoute: typeof rootRouteImport }
    '/watch': { id: '/watch'; path: '/watch'; fullPath: '/watch'; preLoaderRoute: typeof WatchRouteImport; parentRoute: typeof rootRouteImport }
    '/c/$username': { id: '/c/$username'; path: '/c/$username'; fullPath: '/c/$username'; preLoaderRoute: typeof CUsernameRouteImport; parentRoute: typeof rootRouteImport }
    '/playlists': { id: '/playlists'; path: '/playlists'; fullPath: '/playlists'; preLoaderRoute: typeof PlaylistsRouteImport; parentRoute: typeof rootRouteImport }
    '/playlist/$playlistId': { id: '/playlist/$playlistId'; path: '/playlist/$playlistId'; fullPath: '/playlist/$playlistId'; preLoaderRoute: typeof PlaylistPlaylistIdRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = { IndexRoute, AdminRoute, AuthRoute, CommunityRoute, ExploreRoute, NotificationsRoute, PartnerRoute, RulesRoute, SettingsRoute, UploadRoute, WatchRoute, CUsernameRoute, PlaylistsRoute, PlaylistPlaylistIdRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> } }
